/**
 * GLOBAL VARIABLES
 */
export const GLOBAL_PATH_NAME = "GLOBAL_PATH_NAME";
export const GLOBAL_WALLET_CONNECTED = "GLOBAL_WALLET_CONNECTED";
export const GLOBAL_WALLET_CONNECT_MODAL_SHOW =
  "GLOBAL_WALLET_CONNECT_MODAL_SHOW";
export const GLOBAL_SETTING_TD_SAVED = "GLOBAL_SETTING_TD_SAVED";
export const GLOBAL_SETTING_TD_SELECTED = "GLOBAL_SETTING_TD_SELECTED";
export const GLOBAL_SETTING_REFLECT_SAVED = "GLOBAL_SETTING_REFLECT_SAVED";
export const GLOBAL_SETTING_REFLECT_SELECTED =
  "GLOBAL_SETTING_REFLECT_SELECTED";
export const GLOBAL_SETTING_SIGNAL_SAVED = "GLOBAL_SETTING_SIGNAL_SAVED";
export const GLOBAL_SETTING_SIGNAL_SELECTED = "GLOBAL_SETTING_SIGNAL_SELECTED";
export const GLOBAL_FIELD_DATA = "GLOBAL_FIELD_DATA";
export const GLOBAL_FIELD_SELECTED = "GLOBAL_FIELD_SELECTED";
export const NFT_MARKETPLACE_SHOW = "NFT_MARKETPLACE_SHOW";

/**
 * NAVBAR VARIABLES
 */
export const LEFT_NAVBAR_SHOW = "LEFT_NAVBAR_SHOW";
export const LEFT_NAVBAR_PAGE_SELECTED = "LEFT_NAVBAR_PAGE_SELECTED";
export const RIGHT_NAVBAR_SHOW = "RIGHT_NAVBAR_SHOW";
export const RIGHT_NAVBAR_TAB_SELECTED = "RIGHT_NAVBAR_TAB_SELECTED";
export const RIGHT_NAVBAR_SUB_TAB_SELECTED = "RIGHT_NAVBAR_SUB_TAB_SELECTED";
export const RIGHT_NAVBAR_MAX_VALUE = "RIGHT_NAVBAR_MAX_VALUE";
export const RIGHT_NAVBAR_CUR_VALUE = "RIGHT_NAVBAR_CUR_VALUE";
export const RIGHT_NAVBAR_NFT_SELECTED = "RIGHT_NAVBAR_NFT_SELECTED";
export const RIGHT_NAVBAR_ASSET_SELECTED = "RIGHT_NAVBAR_ASSET_SELECTED";
export const RIGHT_NAVBAR_EMISSION_SELECTED = "RIGHT_NAVBAR_EMISSION_SELECTED";
export const RIGHT_NAVBAR_STEP_SELECTED = "RIGHT_NAVBAR_STEP_SELECTED";
export const RIGHT_NAVBAR_NFT_EQUIVALENT_AMOUNT =
  "RIGHT_NAVBAR_NFT_EQUIVALENT_AMOUNT";
export const RIGHT_NAVBAR_DEPOSIT_VALUE = "RIGHT_NAVBAR_DEPOSIT_VALUE";
export const RIGHT_NAVBAR_INDICATOR_FLAG = "RIGHT_NAVBAR_INDICATOR_FLAG";
export const DEPOSIT_DATA = "DEPOSIT_DATA";
